// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkrnmbptlshfgwgosdqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcm5tYnB0bHNoZmd3Z29zZHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MDI3MDksImV4cCI6MjA1NDI3ODcwOX0.IijBR5RKcxWYLatAnc4F6XHWQWMbVov-d38Yk8byivU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);